majime3main: majime3main.o majime3-2.o stdafx.o
	g++ -Wall -o majime3main majime3main.o majime3-2.o 
stdafx.o: stdafx.cpp
	g++ -Wall -c stdafx.cpp
majime3-2.o: majime3-2.cpp
	g++ -Wall -c majime3-2.cpp 
majime3main.o: majime3main.cpp
	g++ -Wall -c majime3main.cpp
clean:
	rm -f *.o majime3main