majigaba1main: majigaba1main.o majigaba1.o stdafx.o
	g++ -Wall -o majigaba1main majigaba1main.o majigaba1.o 
stdafx.o: stdafx.cpp
	g++ -Wall -c stdafx.cpp
majigaba1.o: majigaba1.cpp
	g++ -Wall -c majigaba1.cpp 
majigaba1main.o: majigaba1main.cpp
	g++ -Wall -c majigaba1main.cpp
clean:
	rm -f *.o majigaba1main